# Generated by Django 5.1.1 on 2024-09-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyblock',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='CAD', max_length=3),
            preserve_default=False,
        ),
    ]
