# Generated by Django 5.1.1 on 2024-10-04 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
